import ChatLink from "@/components/chat-link";

// generate 100 fake chat links with random scientific and computer related names
const fakeChatLinksToIds = [
	{ id: "chat-1", name: "Quantum Entanglement" },
	{ id: "chat-2", name: "Neural Networks" },
	{ id: "chat-3", name: "Genetic Algorithms" },
	{ id: "chat-4", name: "Particle Physics" },
	{ id: "chat-5", name: "Astrophysics" },
	{ id: "chat-6", name: "Molecular Biology" },
	{ id: "chat-7", name: "Cryptography" },
	{ id: "chat-8", name: "Machine Learning" },
	{ id: "chat-9", name: "Data Structures" },
	{ id: "chat-10", name: "Operating Systems" },
	{ id: "chat-11", name: "Software Engineering" },
	{ id: "chat-12", name: "Blockchain" },
	{ id: "chat-13", name: "Artificial Intelligence" },
	{ id: "chat-14", name: "Cloud Computing" },
	{ id: "chat-15", name: "Quantum Computing" },
	{ id: "chat-16", name: "Deep Learning" },
	{ id: "chat-17", name: "Computer Vision" },
	{ id: "chat-18", name: "Natural Language" },
	{ id: "chat-19", name: "Bioinformatics" },
	{ id: "chat-20", name: "Nanotechnology" },
	{ id: "chat-21", name: "Cyber Security" },
	{ id: "chat-22", name: "Robotics" },
	{ id: "chat-23", name: "Algorithms" },
	{ id: "chat-24", name: "Database Systems" },
	{ id: "chat-25", name: "Network Protocols" },
	{ id: "chat-26", name: "Distributed Systems" },
	{ id: "chat-27", name: "Cosmology" },
	{ id: "chat-28", name: "Thermodynamics" },
	{ id: "chat-29", name: "Fluid Dynamics" },
	{ id: "chat-30", name: "Quantum Mechanics" },
	{ id: "chat-31", name: "Relativity Theory" },
	{ id: "chat-32", name: "String Theory" },
	{ id: "chat-33", name: "Black Holes" },
	{ id: "chat-34", name: "Dark Matter" },
	{ id: "chat-35", name: "Supernova Events" },
	{ id: "chat-36", name: "Exoplanet Studies" },
	{ id: "chat-37", name: "Neuroscience" },
	{ id: "chat-38", name: "Genomics" },
	{ id: "chat-39", name: "Protein Folding" },
	{ id: "chat-40", name: "CRISPR Technology" },
	{ id: "chat-41", name: "Quantum Cryptography" },
	{ id: "chat-42", name: "GPU Computing" },
	{ id: "chat-43", name: "Tensor Networks" },
	{ id: "chat-44", name: "Reinforcement Learning" },
	{ id: "chat-45", name: "Neural Plasticity" },
	{ id: "chat-46", name: "Photonics" },
	{ id: "chat-47", name: "Semiconductor Physics" },
	{ id: "chat-48", name: "Plasma Physics" },
	{ id: "chat-49", name: "Geophysics" },
	{ id: "chat-50", name: "Atmospheric Science" },
	{ id: "chat-51", name: "Climate Modeling" },
	{ id: "chat-52", name: "Seismic Analysis" },
	{ id: "chat-53", name: "Oceanography" },
	{ id: "chat-54", name: "Ecology Systems" },
	{ id: "chat-55", name: "Evolution Theory" },
	{ id: "chat-56", name: "Paleontology" },
	{ id: "chat-57", name: "Microbiology" },
	{ id: "chat-58", name: "Immunology" },
	{ id: "chat-59", name: "Virology" },
	{ id: "chat-60", name: "Pharmacology" },
	{ id: "chat-61", name: "Synthetic Biology" },
	{ id: "chat-62", name: "Biomedical Engineering" },
	{ id: "chat-63", name: "Medical Imaging" },
	{ id: "chat-64", name: "Epidemiology" },
	{ id: "chat-65", name: "Oncology Research" },
	{ id: "chat-66", name: "Neurotransmitters" },
	{ id: "chat-67", name: "Endocrinology" },
	{ id: "chat-68", name: "Cardiology Data" },
	{ id: "chat-69", name: "Pulmonary Science" },
	{ id: "chat-70", name: "Gastroenterology" },
	{ id: "chat-71", name: "Nephrology Studies" },
	{ id: "chat-72", name: "Dermatology" },
	{ id: "chat-73", name: "Orthopedics" },
	{ id: "chat-74", name: "Psychiatry" },
	{ id: "chat-75", name: "Psychology Insights" },
	{ id: "chat-76", name: "Sociology Trends" },
	{ id: "chat-77", name: "Anthropology" },
	{ id: "chat-78", name: "Archaeology" },
	{ id: "chat-79", name: "Linguistics" },
	{ id: "chat-80", name: "Cryptanalysis" },
	{ id: "chat-81", name: "Information Theory" },
	{ id: "chat-82", name: "Coding Theory" },
	{ id: "chat-83", name: "Signal Processing" },
	{ id: "chat-84", name: "Image Processing" },
	{ id: "chat-85", name: "Pattern Recognition" },
	{ id: "chat-86", name: "Optimization Theory" },
	{ id: "chat-87", name: "Graph Theory" },
	{ id: "chat-88", name: "Category Theory" },
	{ id: "chat-89", name: "Abstract Algebra" },
	{ id: "chat-90", name: "Real Analysis" },
	{ id: "chat-91", name: "Complex Numbers" },
	{ id: "chat-92", name: "Topology" },
	{ id: "chat-93", name: "Geometry" },
	{ id: "chat-94", name: "Number Theory" },
	{ id: "chat-95", name: "Combinatorics" },
	{ id: "chat-96", name: "Probability Theory" },
	{ id: "chat-97", name: "Statistics" },
	{ id: "chat-98", name: "Bayesian Methods" },
	{ id: "chat-99", name: "Monte Carlo" },
	{ id: "chat-100", name: "Chaos Theory" },
];

export default async function ChatList({ params }: { params: Promise<{ slug: string }> }) {

	return (
		<div className=" overflow-y-scroll">
			<div className="flex flex-col gap-y-2 ">
				{fakeChatLinksToIds.map((chat) => {
					return <ChatLink key={chat.id} chatId={chat.id} name={chat.name} />;
				})}
			</div>
		</div>
	)
}
